version: '3'

vars:
  OLLAMA_MODEL: qwen2.5:0.5b

tasks:
  up:
    desc: Start all services
    cmds:
      - docker compose up -d --build
      - echo ""
      - echo "Waiting for bootstrap..."
      - docker compose logs -f bootstrap 2>/dev/null || true
      - echo ""
      - echo "Pulling model..."
      - docker exec ollama ollama pull {{.OLLAMA_MODEL}}
      - echo ""
      - echo "Ready."
      - echo "  Vault:  http://localhost:8200 (token: root)"
      - echo "  Consul: http://localhost:8500"
      - echo ""
      - echo "Run: task demo"

  down:
    desc: Stop all services
    cmds:
      - docker compose down

  clean:
    desc: Stop services and remove volumes
    cmds:
      - docker compose down -v

  demo:
    desc: Guided walkthrough of intentions and mTLS
    cmds:
      - task: _demo_intro
      - task: _demo_deny
      - task: _demo_allow
      - task: _demo_break
      - task: _demo_end

  chat:
    desc: Interactive chat
    cmds:
      - python3 scripts/chat.py

  allow:
    desc: Create intentions (allow traffic)
    cmds:
      - docker exec consul consul intention create planner-agent executor-agent 2>/dev/null || docker exec consul consul intention create -replace planner-agent executor-agent
      - docker exec consul consul intention create executor-agent ollama 2>/dev/null || docker exec consul consul intention create -replace executor-agent ollama
      - echo "Intentions created"
      - docker exec consul consul intention list

  deny:
    desc: Delete intentions (block traffic)
    cmds:
      - docker exec consul consul intention delete planner-agent executor-agent 2>/dev/null || true
      - docker exec consul consul intention delete executor-agent ollama 2>/dev/null || true
      - echo "Intentions deleted"

  logs:
    desc: Follow all logs
    cmds:
      - docker compose logs -f

  # === Internal tasks (no desc = hidden from task --list) ===

  _demo_intro:
    cmds:
      - |
        echo ""
        echo "Agentic AI SPIFFE Demo"
        echo "======================"
        echo ""
        echo "Open Consul UI: http://localhost:8500"
        echo ""
        echo "This demo shows:"
        echo "  1. Default deny - no intentions, no traffic"
        echo "  2. Create intentions - traffic flows"
        echo "  3. Remove intention - traffic stops"
        echo ""
        read -p "Press Enter to start..."

  _demo_deny:
    cmds:
      - |
        echo ""
        echo "Step 1: Default Deny"
        echo "--------------------"
        echo "Deleting all intentions..."
      - task: deny
      - sleep 2
      - |
        echo ""
        echo "Testing request (should fail)..."
        echo ""
      - task: _test
      - |
        echo ""
        read -p "Press Enter to continue..."

  _demo_allow:
    cmds:
      - |
        echo ""
        echo "Step 2: Allow Traffic"
        echo "---------------------"
        echo "Creating intentions..."
      - task: allow
      - sleep 2
      - |
        echo ""
        echo "Testing request (should work)..."
        echo ""
      - task: _test
      - |
        echo ""
        read -p "Press Enter to continue..."

  _demo_break:
    cmds:
      - |
        echo ""
        echo "Step 3: Break One Link"
        echo "----------------------"
        echo "Removing planner → executor intention..."
      - docker exec consul consul intention delete planner-agent executor-agent
      - sleep 2
      - |
        echo ""
        echo "Testing request (should fail)..."
        echo ""
      - task: _test
      - |
        echo ""
        read -p "Press Enter to continue..."

  _demo_end:
    cmds:
      - task: allow
      - |
        echo ""
        echo "Demo complete."
        echo ""
        echo "Try: task chat"
        echo ""

  _test:
    cmds:
      - |
        response=$(curl -s -w "\n%{http_code}" http://localhost:8080/ask \
          -H "Content-Type: application/json" \
          -d '{"question": "Say hello in 5 words or less"}')
        body=$(echo "$response" | head -n -1)
        code=$(echo "$response" | tail -n 1)
        if [ "$code" = "200" ]; then
          echo "OK: $(echo "$body" | jq -r '.answer' 2>/dev/null || echo "$body")"
        else
          echo "BLOCKED (HTTP $code)"
        fi
