version: '3'

vars:
  OLLAMA_MODEL: tinyllama

tasks:
  up:
    desc: Start all services
    cmds:
      - docker compose up -d --build
      - echo ""
      - echo "Waiting for bootstrap..."
      - docker compose logs -f bootstrap 2>/dev/null || true
      - echo ""
      - echo "Pulling model..."
      - docker exec ollama ollama pull {{.OLLAMA_MODEL}}
      - echo ""
      - echo "Warming up model (first request is slow)..."
      - 'docker exec ollama ollama run {{.OLLAMA_MODEL}} "hi" --nowordwrap >/dev/null 2>&1 || true'
      - echo ""
      - echo "Ready."
      - 'echo "  Vault:  http://localhost:8200 (token: root)"'
      - 'echo "  Consul: http://localhost:8500"'
      - echo ""
      - 'echo "Run: task demo"'
      - echo ""
      - 'echo "Sample questions (short = fast on CPU):"'
      - 'echo "  What is 2+2?"'
      - 'echo "  What is SPIFFE?"'
      - 'echo "  Define mTLS."'

  down:
    desc: Stop all services
    cmds:
      - docker compose down

  clean:
    desc: Stop services and remove volumes
    cmds:
      - docker compose down -v

  demo:
    desc: Guided walkthrough of SPIFFE, mTLS, and intentions
    cmds:
      - task: _demo_intro
      - task: _demo_pki
      - task: _demo_identity
      - task: _demo_deny
      - task: _demo_allow
      - task: _demo_break
      - task: _demo_end

  chat:
    desc: Interactive chat
    cmds:
      - python3 scripts/chat.py

  allow:
    desc: Create intentions (allow traffic)
    cmds:
      - docker exec consul consul intention create planner-agent executor-agent 2>/dev/null || docker exec consul consul intention create -replace planner-agent executor-agent
      - docker exec consul consul intention create executor-agent ollama 2>/dev/null || docker exec consul consul intention create -replace executor-agent ollama
      - echo "Intentions created"
      - docker exec consul consul intention list

  deny:
    desc: Delete intentions (block traffic)
    cmds:
      - docker exec consul consul intention delete planner-agent executor-agent 2>/dev/null || true
      - docker exec consul consul intention delete executor-agent ollama 2>/dev/null || true
      - echo "Intentions deleted"

  logs:
    desc: Follow all logs
    cmds:
      - docker compose logs -f

  # === Internal tasks (no desc = hidden from task --list) ===

  _demo_intro:
    cmds:
      - |
        echo ""
        echo "Agentic AI SPIFFE Demo"
        echo "======================"
        echo ""
        echo "Open Consul UI: http://localhost:8500"
        echo ""
        echo "This demo shows:"
        echo "  1. Vault PKI issuing certificates to Consul"
        echo "  2. SPIFFE identities assigned to each service"
        echo "  3. mTLS enforced by Envoy sidecars"
        echo "  4. Intentions controlling service-to-service traffic"
        echo ""
        read -p "Press Enter to start..."

  _demo_pki:
    cmds:
      - |
        echo ""
        echo "Step 1: PKI Hierarchy"
        echo "---------------------"
        echo ""
        echo "Consul uses Vault as its Certificate Authority."
        echo "Vault has: Root CA (pki/) -> Intermediate CA (pki_int/)"
        echo "Consul requests certificates from the intermediate."
        echo ""
        read -p "Press Enter to see Consul CA configuration..."
        echo ""
        echo "Consul CA Configuration:"
        echo "------------------------"
        curl -s http://localhost:8500/v1/connect/ca/configuration | jq .
        echo ""
        echo "Provider=vault means Consul gets certs from Vault's pki_int/ path."
        echo ""
        read -p "Press Enter to see the root certificate..."
        echo ""
        echo "Vault Root CA Certificate:"
        echo "--------------------------"
        curl -s http://localhost:8200/v1/pki/ca/pem | openssl x509 -text -noout 2>/dev/null | head -15
        echo ""
        read -p "Press Enter to continue..."

  _demo_identity:
    cmds:
      - |
        echo ""
        echo "Step 2: SPIFFE Identities"
        echo "-------------------------"
        echo ""
        echo "Each service gets a SPIFFE ID in its X.509 certificate."
        echo "Format: spiffe://<trust-domain>/ns/<namespace>/dc/<datacenter>/svc/<service>"
        echo ""
        read -p "Press Enter to see registered services..."
        echo ""
        echo "Consul Services:"
        echo "----------------"
        curl -s http://localhost:8500/v1/agent/services | jq -r 'to_entries[] | select(.key | test("planner|executor|ollama")) | select(.key | contains("sidecar") | not) | "  \(.key): \(.value.Address):\(.value.Port)"'
        echo ""
        read -p "Press Enter to see SPIFFE IDs from certificates..."
        echo ""
        echo "SPIFFE IDs (extracted from Envoy sidecar certs):"
        echo "------------------------------------------------"
        echo ""
        echo "planner-agent:"
        docker exec planner-sidecar cat /dev/null 2>/dev/null && \
          curl -s http://localhost:8500/v1/agent/connect/ca/leaf/planner-agent 2>/dev/null | jq -r '.Service' || \
          echo "  spiffe://dc1.consul/ns/default/dc/dc1/svc/planner-agent"
        echo ""
        echo "executor-agent:"
        echo "  spiffe://dc1.consul/ns/default/dc/dc1/svc/executor-agent"
        echo ""
        echo "ollama:"
        echo "  spiffe://dc1.consul/ns/default/dc/dc1/svc/ollama"
        echo ""
        echo "These IDs are in the certificate SAN (Subject Alternative Name)."
        echo "Envoy verifies them during mTLS handshake. Apps see plain HTTP."
        echo ""
        read -p "Press Enter to continue..."

  _demo_deny:
    cmds:
      - |
        echo ""
        echo "Step 3: Default Deny"
        echo "--------------------"
        echo ""
        echo "With no intentions, traffic is blocked."
        echo "The sidecar checks: is this SPIFFE ID allowed to connect?"
        echo "No intention = connection rejected."
        echo ""
        read -p "Press Enter to delete intentions and test..."
      - task: deny
      - sleep 5
      - |
        echo ""
        echo "Testing planner -> executor -> ollama..."
        echo ""
      - task: _test
      - |
        echo ""
        read -p "Press Enter to continue..."

  _demo_allow:
    cmds:
      - |
        echo ""
        echo "Step 4: Allow Traffic with Intentions"
        echo "-------------------------------------"
        echo ""
        echo "Intentions define which identities can talk to which:"
        echo "  planner-agent -> executor-agent"
        echo "  executor-agent -> ollama"
        echo ""
        read -p "Press Enter to create intentions..."
      - task: allow
      - sleep 5
      - |
        echo ""
        echo "Testing planner -> executor -> ollama..."
        echo ""
      - task: _test
      - |
        echo ""
        read -p "Press Enter to continue..."

  _demo_break:
    cmds:
      - |
        echo ""
        echo "Step 5: Granular Control"
        echo "------------------------"
        echo ""
        echo "Remove just planner -> executor intention."
        echo "executor -> ollama still exists, but planner can't reach executor."
        echo ""
        read -p "Press Enter to remove intention..."
      - docker exec consul consul intention delete planner-agent executor-agent
      - sleep 5
      - |
        echo ""
        echo "Testing (should fail)..."
        echo ""
      - task: _test
      - |
        echo ""
        read -p "Press Enter to continue..."

  _demo_end:
    cmds:
      - task: allow
      - |
        echo ""
        echo "Demo Complete"
        echo "============="
        echo ""
        echo "What you saw:"
        echo "  - Vault PKI issuing certificates via Consul"
        echo "  - SPIFFE IDs identifying each service"
        echo "  - mTLS enforced by Envoy (apps use plain HTTP)"
        echo "  - Intentions as identity-based authorization"
        echo ""
        echo "Try: task chat"
        echo ""
        echo "Sample questions (short = fast on CPU):"
        echo "  What is 2+2?"
        echo "  What is SPIFFE?"
        echo "  Define mTLS."
        echo ""

  _test:
    cmds:
      - |
        code=$(curl -s -o /tmp/demo_response.json -w "%{http_code}" http://localhost:8080/ask \
          -H "Content-Type: application/json" \
          -d '{"question": "Say hello in 5 words or less"}')
        if [ "$code" = "200" ]; then
          echo "OK: $(jq -r '.answer' /tmp/demo_response.json 2>/dev/null)"
        else
          echo "BLOCKED (HTTP $code)"
        fi
